INSERT INTO book (image, author, title, description, type, price, editorial, idioma, paginas, publicacion, formato) VALUES
(
  'https://www.rae.es/sites/default/files/portada_cien_anos_de_soledad_0.jpg',
  'Gabriel García Márquez',
  '100 años de soledad',
  'Cien años de soledad es una novela del escritor colombiano Gabriel García Márquez, publicada en 1967. Es considerada una de las obras más importantes de la literatura en español y un clásico del realismo mágico.',
  'digital',
  1000,
  'Editorial Sudamericana',
  'Español',
  471,
  1967,
  'EPUB'
),
(
  'https://www.agenciabalcells.com/fileadmin/_processed_/csm_LRH_el-amor-en-los-tiempos-del-colera_221b9c6e61.jpg',
  'Gabriel García Márquez',
  'El amor en los tiempos del cólera',
  'El amor en los tiempos del cólera es una novela del escritor colombiano Gabriel García Márquez, publicada en 1985. La historia sigue la vida de Florentino Ariza y Fermina Daza, quienes se enamoran en su juventud pero se separan por circunstancias de la vida.',
  'fisico',
  3000,
  'Editorial Oveja Negra',
  'Español',
  348,
  1985,
  'Tapa blanda'
),
(
  'https://laplumadeluder.com/wp-content/uploads/2018/12/Portada_El_Principito.jpg',
  'Antoine de Saint-Exupéry',
  'El principito',
  'El principito es una novela corta del escritor francés Antoine de Saint-Exupéry, publicada en 1943. La historia sigue a un joven príncipe que viaja por diferentes planetas y aprende lecciones sobre la vida y la naturaleza humana.',
  'fisico',
  7700,
  'Editorial Salamandra',
  'Español',
  96,
  1943,
  'Tapa dura'
),
(
  'https://librerialerner.vtexassets.com/arquivos/ids/1358182-1200-auto?v=638459794864200000&width=1200&height=auto&aspect=true',
  'Joseph Stiglitz',
  'El capitalismo progresista',
  'El capitalismo progresista es un libro del economista y político estadounidense Joseph Stiglitz, publicado en 2019. En él, Stiglitz argumenta que el capitalismo puede ser una fuerza positiva para el progreso social y económico si se implementan políticas adecuadas.',
  'digital',
  3700,
  'Taurus',
  'Español',
  432,
  2019,
  'PDF'
),
(
  'https://static.cegal.es/imagenes/marcadas/9788466/978846622779.gif',
  'Miguel de Cervantes',
  'El Quijote de la Mancha',
  'El ingenioso hidalgo don Quijote de la Mancha es una novela del escritor español Miguel de Cervantes, publicada en 1605. La historia sigue las aventuras de un noble que se vuelve loco y decide convertirse en caballero andante.',
  'fisico',
  5000,
  'Espasa',
  'Español',
  1344,
  1605,
  'Tapa dura'
),
(
  'https://images.cdn3.buscalibre.com/fit-in/360x360/7e/31/7e31e989a8deb0efd8d6c058e7262530.jpg',
  'Gabriel García Márquez',
  'Macondo',
  'Macondo es un pueblo ficticio creado por el escritor colombiano Gabriel García Márquez, que aparece en varias de sus obras, incluyendo "Cien años de soledad". Macondo es un lugar mágico y surrealista que representa la historia y la cultura de América Latina.',
  'digital',
  4000,
  'Vintage Español',
  'Español',
  224,
  2021,
  'EPUB'
);